login:
  username: "argo"
  password: "argo123"
  email: "argo@recar.com"
  phone: "18888888888"
browser:
  unheadless: false # 开启则界面
  trace: false # 有界面时显示点击了哪些
  tab_count: 10 # 最多开启多个tab页面
  proxy: ""
  tab_timeout: 30 # tab页面最长时间
  browser_timeout: 18000 # 浏览器运行最长时间
  max_depth: 10 # 爬行最大深度
auto:
  slow: 1000 # 事件触发的延迟时间
  filter: ["lougout", "登出", "reset"] # 包含这种字符的就不进行触发事件
