name: 🎉 Build Binary

on:
  push:
    tags:
      - v*

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.40
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19
          binary_name: "argo"
          project_path: "./cmd/argo.go "
          build_flags: "-X main.Version=${{ steps.get_version.outputs.VERSION }}"
          extra_files: README.md
